SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
FPS = 60

# AI Config
POPULATION_SIZE = 50
SENSOR_COUNT = 5
SENSOR_LENGTH = 150
HIDDEN_NODES = 6

# Genetic Config
MUTATION_RATE = 0.1
GENOME_SIZE = (SENSOR_COUNT * HIDDEN_NODES) + (HIDDEN_NODES * 2)